
services:
  caddy:
    image: caddy:2.10.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/caddy
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      edge:
        aliases:
          - auth.test.internal
          - grafana.test.internal
          - zabbix.test.internal
          - whoami.test.internal
volumes:
  caddy_data:
  caddy_config:
networks:
  edge:
    name: local-services-network
    external: true
