
services:
  caddy:
    image: caddy:2.10.2
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
      - "8443:443/udp"

    volumes:
      - ./conf:/etc/caddy
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - edge
volumes:
  caddy_data:
  caddy_config:
networks:
  edge:
    name: local-services-network
    external: true
