services:
  grafana:
    build: .
    image: grafana-custom
    container_name: grafana
    restart: unless-stopped
    networks:
      - edge
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./caddy-root.crt:/usr/local/share/ca-certificates/caddy-root.crt:ro
    environment:
      - GF_AUTH_GENERIC_OAUTH_ENABLED=${GF_AUTH_GENERIC_OAUTH_ENABLED}
      - GF_AUTH_GENERIC_OAUTH_NAME=${GF_AUTH_GENERIC_OAUTH_NAME}
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=${GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${GF_AUTH_GENERIC_OAUTH_CLIENT_ID}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}
      - GF_AUTH_GENERIC_OAUTH_SCOPES=${GF_AUTH_GENERIC_OAUTH_SCOPES}
      - GF_AUTH_GENERIC_OAUTH_DISCOVERY_URL=https://auth.test.internal/application/o/grafana/.well-known/openid-configuration
      - GF_AUTH_GENERIC_OAUTH_USE_PKCE=${GF_AUTH_GENERIC_OAUTH_USE_PKCE}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE=true
      - GF_AUTH_GENERIC_OAUTH_SKIP_TLS_VERIFY=true

volumes:
  grafana_data:

networks:
  edge:
    external: true
    name: local-services-network